# Generated by Django 5.2.8 on 2026-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('notes', 'Notes'), ('electronics', 'Electronics'), ('stationery', 'Stationery'), ('lab-materials', 'Lab Materials'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('free', 'Free'), ('exchange', 'Exchange Only')], default='used', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='exchange_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resource_images/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
